/* eslint-disable no-unused-vars */
export enum Keywords {
    DigikalaLogo = "لوگوی دیجیکالا",
    searchPlaceholder = "جستجو",
    login = "ورود",
    sigUp = "ثبت نام",
    productsClassification = "دسته‌بندی کالاها",
    surprisingProducts = "شگفت انگیز ها",
    supermarket = "سوپرمارکت",
    giftCard = "کارت هدیه",
    topSales = "پرفروش ترین ها",
    discounter = "تخفیف ها و پیشنهاد ها",
    haveQuestion = "سوالی دارید؟",
    saleAtDigikala = "در دیجی کالا بفروشید!",
    chooseLocation = "لطفا شهر خود را انتخاب کنید",
    topSales5 = "",
    topSales6 = "",
    topSales7 = "",
    toman = "تومان",
    offTo59 = "تا ۵۹٪ تخفیف",
    moreThan100Product = "بیش از ۱۰۰ کالا",
    buyBaseOnClasification = "خرید بر اساس دسته بندی",
    surprisingOffer = 'پیشنهاد شگفت انگیز',
    digikalaOffer = 'پیشنهاد دیجی کالا',
    PopularBrands = 'محبوب ترین برند ها',
    BaseOnYourVisit = 'بر اساس بازدید های شما',
    Visit = 'مشاهده',
    ForDigiPlusMembers = 'خدمت ویژه برای اعضای دیجی‌پلاس',
    Membership = 'عضویت',
    FreeDelivery = 'ارسال فوری رایگان',
    seeAll = "مشاهده همه",
    YourPoint = "امتیاز شما",
    BestSellerProducts = "پرفروش ترین کالا ها"
  }